# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc65f0084cb83fb0c1e7e5ddc451d7807ad72a09cb359ad69ae9b99bb6c63909dbf361e3994877084ac6197668d6a297801484b940e72393f9c8312d7f7a8d36

test:
  secret_key_base: ada90850bebed1c8b0270b556fc8b420ca6b752c77b1dd24344b3fb51217470f05ec43c92e9391a7905baa9de95a62c1b26f75fbaf37f6942322056b7ad90c50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
